# Generated by Django 5.1.7 on 2025-03-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
